[env:esp32-s3n16r16]
platform = espressif32
board = esp32-s3-devkitc1-n16r16
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
lib_deps =
  bblanchon/ArduinoJson @ ^7.1.0
  moononournation/GFX Library for Arduino @ ^1.6.6
